version: '3.0'

services:
  db:
    image: postgres:13
    container_name: pg_server_auth
    networks:
      - backend_nw
    volumes:
      - pg_data_auth:/var/lib/postgresql/data
    env_file:
      - ./.postgres_auth.env
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.6
    container_name: redis
    networks:
      - backend_nw
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend_nw
    volumes:
      - code_api_auth:/code
    env_file:
      - .auth.env
    entrypoint: 
      - entrypoint.sh
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis

volumes:
  code:
  code_api_auth:
  pg_data_auth:
  redis_data:

networks:
  backend_nw:
    driver: bridge

