"""add social_account

Revision ID: 114fd63d1e74
Revises: 73b414e7b1bc
Create Date: 2022-05-26 22:02:19.032544

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "114fd63d1e74"
down_revision = "73b414e7b1bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_account",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("social_id", sa.String(), nullable=False),
        sa.Column("social_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("social_id", "social_name", name="social_pk"),
    )
    op.create_unique_constraint(None, "roles", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    op.create_unique_constraint(None, "users_access_history", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_access_history", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_table("social_account")
    # ### end Alembic commands ###
