"""add email to user

Revision ID: 352bbeb9587c
Revises: 114fd63d1e74
Create Date: 2022-05-26 22:46:09.131179

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "352bbeb9587c"
down_revision = "114fd63d1e74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "social_account", ["id"])
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email")
    op.drop_constraint(None, "social_account", type_="unique")
    # ### end Alembic commands ###
