"""add totp fields to history

Revision ID: 80b7fbae38fc
Revises: e658a710fe7e
Create Date: 2022-05-29 13:43:11.267476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b7fbae38fc'
down_revision = 'e658a710fe7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_access_history', sa.Column('request_id', sa.String(), nullable=False))
    op.add_column('users_access_history', sa.Column('totp_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_access_history', 'totp_status')
    op.drop_column('users_access_history', 'request_id')
    # ### end Alembic commands ###
